# Generated by Django 3.2.7 on 2021-09-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehub', '0002_remove_game_added_users'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='musts',
            field=models.ManyToManyField(to='gamehub.Game'),
        ),
    ]
