version: '3'


services:
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    env_file:
      - ./.env.db
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - '5432:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'
    restart: always

  celery-beat:
    build: .
    command: celery -A config beat
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
      - redis
      - app

  celery:
    build: .
    command: celery -A config worker -l INFO --pool=solo
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
      - redis
      - app
      - celery-beat

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - app
      - db
    ports:
      - '80:80'