# Generated by Django 3.2.7 on 2021-09-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamehub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='added_users',
        ),
    ]
